### ISSUE TITLE
Esilehe tutvustuse ja pildi paigutus

### ISSUE THREAD

**Issue by martintrumann** [martintrumann/ac-cd-leht#12]
Teksti ja pildi suhe peab olema samasugune nagu alloleval pildil.
![screenshot](https://user-images.githubusercontent.com/44016775/71065933-eaf6f000-217a-11ea-9817-f086baa8856e.png)

**Comment by randoschool** [comment]
@martintrumann Kas mingi Figma lingi saaks ka, et värve ja suuruseid vaadata?
